language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls codecov

script:
  - py.test --cov-report term-missing --cov app

after-success:
  - coveralls
  - codecov
